@echo off

REM echo chipmunk for noCTD noRif peaks 1..
REM java -jar C:\Sutor\Dists\chipmunk.jar s:C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_noCTD_noRif_rep123_nm_0.001_peaks.fasta 1>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_rep123_nm_0.001_peaks_motifs_1.txt 2>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_rep123_nm_0.001_peaks_log_1.txt
REM echo chipmunk for noCTD noRif peaks 2..
REM java -jar C:\Sutor\Dists\chipmunk.jar s:C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_noCTD_noRif_rep123_nm_0.001_peaks.fasta 1>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_rep123_nm_0.001_peaks_motifs_2.txt 2>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_rep123_nm_0.001_peaks_log_2.txt
REM echo chipmunk for noCTD noRif peaks 3..
REM java -jar C:\Sutor\Dists\chipmunk.jar s:C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_noCTD_noRif_rep123_nm_0.001_peaks.fasta 1>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_rep123_nm_0.001_peaks_motifs_3.txt 2>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_rep123_nm_0.001_peaks_log_3.txt
REM 
REM echo chipmunk for noCTD Rif peaks 1..
REM java -jar C:\Sutor\Dists\chipmunk.jar s:C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_noCTD_Rif_rep123_nm_0.001_peaks.fasta 1>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_Rif_rep123_nm_0.001_peaks_motifs_1.txt 2>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_Rif_rep123_nm_0.001_peaks_log_1.txt
REM echo chipmunk for noCTD Rif peaks 2..
REM java -jar C:\Sutor\Dists\chipmunk.jar s:C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_noCTD_Rif_rep123_nm_0.001_peaks.fasta 1>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_Rif_rep123_nm_0.001_peaks_motifs_2.txt 2>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_Rif_rep123_nm_0.001_peaks_log_2.txt
REM echo chipmunk for noCTD Rif peaks 3..
REM java -jar C:\Sutor\Dists\chipmunk.jar s:C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_noCTD_Rif_rep123_nm_0.001_peaks.fasta 1>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_Rif_rep123_nm_0.001_peaks_motifs_3.txt 2>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_Rif_rep123_nm_0.001_peaks_log_3.txt
REM 
REM echo chipmunk for noCTD noRif and noCTD Rif shared peaks 1..
REM java -jar C:\Sutor\Dists\chipmunk.jar s:C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_noCTD_noRif_Rif_rep123_shared_nm_0.001_peaks.fasta 1>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_Rif_rep123_shared_nm_0.001_peaks_motifs_1.txt 2>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_Rif_rep123_shared_nm_0.001_peaks_log_1.txt
REM echo chipmunk for noCTD noRif and noCTD Rif shared peaks 2..
REM java -jar C:\Sutor\Dists\chipmunk.jar s:C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_noCTD_noRif_Rif_rep123_shared_nm_0.001_peaks.fasta 1>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_Rif_rep123_shared_nm_0.001_peaks_motifs_2.txt 2>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_Rif_rep123_shared_nm_0.001_peaks_log_2.txt
REM echo chipmunk for noCTD noRif and noCTD Rif shared peaks 3..
REM java -jar C:\Sutor\Dists\chipmunk.jar s:C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_noCTD_noRif_Rif_rep123_shared_nm_0.001_peaks.fasta 1>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_Rif_rep123_shared_nm_0.001_peaks_motifs_3.txt 2>C:\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_noRif_Rif_rep123_shared_nm_0.001_peaks_log_3.txt

echo chipmunk for CTD noRif peaks 1..
java -jar C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Dists\chipmunk.jar s:C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_CTD_noRif_rep123_nm_0.001_peaks.fasta 1>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_noRif_rep123_nm_0.001_peaks_motifs_1.txt 2>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_noRif_rep123_nm_0.001_peaks_log_1.txt
echo chipmunk for CTD noRif peaks 2..
java -jar C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Dists\chipmunk.jar s:C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_CTD_noRif_rep123_nm_0.001_peaks.fasta 1>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_noRif_rep123_nm_0.001_peaks_motifs_2.txt 2>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_noRif_rep123_nm_0.001_peaks_log_2.txt
echo chipmunk for CTD noRif peaks 3..
java -jar C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Dists\chipmunk.jar s:C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_CTD_noRif_rep123_nm_0.001_peaks.fasta 1>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_noRif_rep123_nm_0.001_peaks_motifs_3.txt 2>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_noRif_rep123_nm_0.001_peaks_log_3.txt

echo chipmunk for CTD Rif peaks 1..
java -jar C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Dists\chipmunk.jar s:C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_CTD_Rif_rep12_nm_0.001_peaks.fasta 1>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_Rif_rep12_nm_0.001_peaks_motifs_1.txt 2>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_Rif_rep12_nm_0.001_peaks_log_1.txt
echo chipmunk for CTD Rif peaks 2..
java -jar C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Dists\chipmunk.jar s:C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_CTD_Rif_rep12_nm_0.001_peaks.fasta 1>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_Rif_rep12_nm_0.001_peaks_motifs_2.txt 2>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_Rif_rep12_nm_0.001_peaks_log_2.txt
echo chipmunk for CTD Rif peaks 3..
java -jar C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Dists\chipmunk.jar s:C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Seq_under_peaks\EcTopoI_CTD_Rif_rep12_nm_0.001_peaks.fasta 1>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_Rif_rep12_nm_0.001_peaks_motifs_3.txt 2>C:\Users\sutor\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_CTD_Rif_rep12_nm_0.001_peaks_log_3.txt

echo sarus for noCTD Rif peaks 1 thr 0..
java -jar C:\OneDrive\ThinkPad_working\Sutor\Dists\sarus-2.0.2.jar C:\OneDrive\ThinkPad_working\Sutor\Science\E_coli_Gyrase_Topo-Seq\Genomes\E_coli_w3110_G_Mu.fasta C:\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_identification\EcTopoI_noCTD_Rif_rep123_nm_0.001_peaks_motifs_1.txt 0 1>C:\OneDrive\ThinkPad_working\Sutor\Science\TopoI-ChIP-Seq\Data_analysis\Motif_scanning\SARUS_new\noCTD_Rif_1_scan_thr_0.txt